// 1. Avval ishni qiladigan funksiyani yozamiz
function add(a, b) {
    return a + b;
}

// 2. Uni eksport qilamiz (robot ko'rishi uchun)
module.exports = { add };

// 3. VA MANA O'SHA QISIM:
if (require.main === module) {
    // Bu faqat 'node src/calculator.js' qilganingda ishlaydi
    setInterval(() => {
        console.log("Dastur ishlayapti...");
    }, 10000);
}
