name: CI Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-gate:
    name: quality-gate / Sifat Darvozasi
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: Node.js o'rnatish
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Kutubxonalarni o'rnatish (Jest bilan birga)
        run: npm install

      - name: Testlarni va Coverage hisobotini ishga tushirish
        run: npm run test:coverage
